γプレゼンで使う用をに調整
TeamT-SEN/T-SEN pull request #107
Opened 2016-12-12 17:35 UTC by kakeru4

今までの作業をγブランチでまとめましたので確認をお願いします。
結構個人的に書いてしまっていますので変更して欲しい場所やここはちがうなどの意見などあればお願いします。
確認したらチェックしてください。
全員がチェックしましたら@Sharoku-hagaさんにマージしてもらいます。

-[] 芳我
-[] 川口
-[] 市川

2016-12-12 17:44 UTC, kakeru4 commented
確認おねがいします！

2016-12-12 18:01 UTC, Sharoku-haga requested changes

2016-12-12 18:01 UTC, Sharoku-haga commented on Twar/Twar/SubScene/Battle.h
> +	LoadingThread*			m_pLoadingThread;
LoadingThreadはモノステイトパターンやから、メンバから消しておいてください。

2016-12-12 18:05 UTC, Sharoku-haga commented on Twar/Twar/SubScene/Battle.h
> +	Light*                  m_pLight;					//!< ライト
ここのLightはどうする？
今後使う可能性があるならこのままメンバとして残しておいてもいいけど、使わないなら消しておくべきかな。

2016-12-12 18:49 UTC, Sharoku-haga requested changes

2016-12-12 18:49 UTC, Sharoku-haga commented on Twar/Twar/SubScene/Battle.h
> +	BulletManager*          m_pBulletManager;
ここのBulletManagerはBattleで使用されていないので、前方宣言も含めて消しておいてください。

2016-12-13 03:45 UTC, kakeru4 commented on Twar/Twar/SubScene/Battle.h
> +	BulletManager*          m_pBulletManager;
すみません、消し忘れです。
修正します。

2016-12-13 03:46 UTC, kakeru4 commented on Twar/Twar/SubScene/Battle.h
> +	LoadingThread*			m_pLoadingThread;
すみません、消し忘れです。
修正します。

2016-12-13 03:47 UTC, kakeru4 commented on Twar/Twar/SubScene/Battle.h
> +	Light*                  m_pLight;					//!< ライト
今のところ使わなさそうなので消しときます。

2016-12-13 09:03 UTC, Sharoku-haga approved these changes

2016-12-13 11:24 UTC, Sharoku-haga commented
修正確認致しましたので、チェックボックスのチェックいれておきました。

2016-12-14 07:17 UTC, kakeru4 commented
一旦マージします。

2016-12-14 11:39 UTC, kakeru4 commented
衝突している部分を全部修正しましたのでマージお願いします。
リベースも完了しています。

2016-12-14 11:41 UTC, merged

2016-12-14 11:41 UTC, Sharoku-haga commented
マージしました

2016-12-14 11:43 UTC, kakeru4 commented
マージしましたのでcloseします。