ライブリの全面改修
TeamT-SEN/T-SEN pull request #19
Opened 2016-10-21 02:39 UTC by Sharoku-haga

#18 の作業になります。

現状ではファイルを作成しただけです。
作業は日曜日に終了予定にしています。
#17 の作業はこちらに合流させます。

2016-10-21 02:39 UTC, review-ninja commented
<a href="https://app.review.ninja/TeamT-SEN/T-SEN/pull/19" target="_blank"><img src="https://app.review.ninja/69837692/pull/19/badge" alt="ReviewNinja"/>

2016-10-21 09:47 UTC, taishi-matsumura commented
GitHubにはレビュワーのリストとか「承認しました」みたいな機能が無いので、ReviewNinjaとかいうプラグインを入れてみました。
最初は「Some checks haven’t completed yet」ってなってるかと思いますが、その下の「Detail」ってとこクリックするとReviewNinjaのサイトに飛ぶので、そこでコードレビューしてコメント書いたりできます。
で、問題無くなれば手裏剣のアイコンをクリックしてNinjaStarをAddしてあげるとGitHub側も「All checks have passed」ってなるので安心してmergeできるという仕組みみたいです。

プルリク上のやり取りもGitHubよりは見易いかと思います。
[これ](https://app.review.ninja/KingdomCraft-1/KingdomCraft/pull/22/657aa2f509e84dd35c33b2c4937c7c7e6f57341b...41ccd69b24802a37210fa827d133c2bb2c48dbd5)とか、森本の鬼の指摘の一覧が見れますね。
ちょっとBitbucketっぽくなる感じ。

2016-10-24 09:05 UTC, Sharoku-haga commented
お疲れ様です。
ライブラリの改修作業でずが、終わったのでreviewお願いします。
個人的に気になる点にはコメントを書いてありますので、良い案があれば大歓迎です。
チェックしてよければ手裏剣お願いします。

2016-10-24 17:48 UTC, taishi-matsumura commented on Twar/Lib_Class/DebugTimer.cpp
> +// �v�����ʂ̎擾
TEXTマクロとかを使ってなさそうなこの辺のファイルはUTF-8化できそうですね。
文字化けウザいのでちょっとずつでも対応お願いします。 !fix

2016-10-24 17:51 UTC, Sharoku-haga commented on Twar/Lib_Class/DebugTimer.cpp
> +// �v�����ʂ̎擾
了解しました。随時UTF-8化進めていきます。

2016-10-24 17:56 UTC, Sharoku-haga commented on Twar/Lib_Class/DebugTimer.cpp
> +// �v�����ʂ̎擾
DubugTimer.cppはUTF-8化して、コミットしました。

2016-10-24 17:57 UTC, taishi-matsumura commented
Lib_Class側のInclude pathとLibrary pathが絶対pathになってます !fix

2016-10-24 18:01 UTC, taishi-matsumura commented
プロジェクトの依存関係を設定して下さい。
現状、Twar側を先にビルドしようとするので、初回はLib_Class.libが無くてエラーになります。
libの方に変更あった場合も、ソリューションを2回ビルドしないとTwar側に最新のlibがリンクされないのでマズいです。 !fix

2016-10-24 18:06 UTC, taishi-matsumura commented on Twar/Lib_Class/DebugTimer.cpp
> +// �v�����ʂ̎擾
!fixed

2016-10-24 18:11 UTC, taishi-matsumura commented on Twar/Lib_Class/Lib_Class.vcxproj
> +    <ClInclude Include="DebugFont.h" />
Lib_Class側のInclude pathとLibrary pathが絶対pathになってます。
あと、その辺りのDebug/Release共通の設定は「すべての構成」に対して設定してやって下さい。 !fix

2016-10-24 18:15 UTC, taishi-matsumura commented on Twar/Lib_Class/Lib_Class.vcxproj
> +    <ClInclude Include="DebugFont.h" />
!fixed

2016-10-24 18:30 UTC, Sharoku-haga commented
Lib_Class側のPath変更とプロジェクト依存関係の設定しました。
すません。Lib_Class側のパスは完全に見落としていました。

2016-10-24 18:41 UTC, taishi-matsumura commented on Twar/Lib_Class/Lib_Class.vcxproj.filters
> +    <ClCompile Include="GraphicsDevice.cpp">
フィルタを細かく設定する前に実ファイル/フォルダの構成を作って下さい。
フィルタはファイルシステム上の木構造を表現する程度にしておいた方が吉です。
includeファイルの相対path指定等あちこち変更が必要になると思うので、UTF-8化と併せて少しずつやっつけていきましょか。 !fix

2016-10-24 18:52 UTC, Sharoku-haga commented on Twar/Lib_Class/Lib_Class.vcxproj.filters
> +    <ClCompile Include="GraphicsDevice.cpp">
了解しました。
フォルダ構成作成後、ファイルごとにincludeファイルの相対path指定変更とUTF-8化
という工程で随時進めていきます。

2016-10-25 18:05 UTC, taishi-matsumura commented on Twar/Lib_Class/Camera/Camera.h
> +﻿/**
doxygenコメント入れてくれてるみたいなので、ついでに。

[ここ](http://cube.atnifty.com/~suzume/wiki/?develop%2Fdoxygen)とかを参考に、doxygenで生成したhtmlファイルをWindowsのヘルプファイル(chm)形式に変換すると捗ります。
読む人向けにchmを、作りたい人向けにdoxyfileを、それぞれリポジトリに入れておくと良いです。(あの大量の.jsとか.htmlとかは不要)
doxyfileは誰のPCでも動くように、各種pathは絶対pathでは無く相対pathで書くように注意。

2016-10-25 18:11 UTC, Sharoku-haga commented
UTF-8化と実フォルダ分け完了しました。
・UTF-8化
reviewninjaでコメントが日本語になっているのを確認いたしました。
別プログラムで試しながら変えましたので、動作も問題ないです。
後、念の為マージテストしてみましたが、文字化けることなくマージもできました。（MergeTestブランチ）
・実フォルダ分け
実フォルダ分けに関してはまず大きくCamera,Light,Font,GameLibで4つに分けております。
更にGameLibフォルダの中でLibフォルダを作成するという形で分けております。

2016-10-25 18:13 UTC, taishi-matsumura commented on Twar/Lib_Class/Lib_Class.vcxproj.filters
> +    <ClCompile Include="GraphicsDevice.cpp">
気長にボチボチやっていって下さい。 !fixed

2016-10-25 18:13 UTC, Sharoku-haga commented on Twar/Lib_Class/Camera/Camera.h
> +﻿/**
了解しました。
作業に入ります。

2016-10-25 18:36 UTC, taishi-matsumura commented on Twar/Lib_Class/GameLib/GameLib.h
> +	void InitGameLib(char* title, int width, int height,HINSTANCE hInstance, LRESULT CALLBACK WndProc(HWND hWnd, UINT msg, WPARAM wp, LPARAM lp), bool windowType);
引数が長すぎて見辛いです。
WndProcは関数ポインタですよね？普通、hWnd等の仮引数は書かないです。
あと、インスタンスハンドルを取得するWin32APIがあった気がするので引数で渡さなくても良いかもです。 !fix

2016-10-25 18:44 UTC, taishi-matsumura commented on Twar/Lib_Class/GameLib/Lib/GraphicsDevice.h
> +	HWND					m_hWnd;			//!< ウィンドウハンドル
メンバで保持する必要ありますか？ !fix

2016-10-25 18:57 UTC, Sharoku-haga commented on Twar/Lib_Class/GameLib/GameLib.h
> +	void InitGameLib(char* title, int width, int height,HINSTANCE hInstance, LRESULT CALLBACK WndProc(HWND hWnd, UINT msg, WPARAM wp, LPARAM lp), bool windowType);
関数ポインタの仮引数はなくしました。
インスタンスハンドルですが、調べたらGetModuleHandle関数で取得できるとのことなので引数からなくし、関数内で取得する形にしました。

2016-10-25 19:20 UTC, taishi-matsumura commented on Twar/Lib_Class/GameLib/GameLib.h
> +	void InitGameLib(char* title, int width, int height,HINSTANCE hInstance, LRESULT CALLBACK WndProc(HWND hWnd, UINT msg, WPARAM wp, LPARAM lp), bool windowType);
これでもまだ長くてイヤですが仕方無いですね。 !fixed

2016-10-25 19:21 UTC, Sharoku-haga commented on Twar/Lib_Class/GameLib/Lib/GraphicsDevice.h
> +	HWND					m_hWnd;			//!< ウィンドウハンドル
必要ないです。
フルスクリーンにするために試行錯誤していたときにメンバに加えて消し忘れてました。
すみません。修正しておきます。

2016-10-25 19:50 UTC, Yottomo commented on Twar/Lib_Class/GameLib/GameLib.h
> +	static GameLib& GetInstance()
GameLib.hのGetInstanceの
コメント間違ってない？

2016-10-25 19:58 UTC, Sharoku-haga commented on Twar/Lib_Class/GameLib/GameLib.h
> +	static GameLib& GetInstance()
すみません。引数消すの忘れてました。後、Singletonの綴りも間違ってます。

2016-10-25 20:14 UTC, Yottomo commented on Twar/Lib_Class/GameLib/GameLib.h
> +﻿/**
DrawFontやStartTimer等の
デバッグ用の関数はデバッグ用であることが分かるように関数名を変更するか、コメントを記述して下さい。

2016-10-25 20:19 UTC, Yottomo commented on Twar/Lib_Class/GameLib/GameLib.h
> +	static GameLib& GetInstance()
!fix

2016-10-25 20:21 UTC, Yottomo commented on Twar/Lib_Class/GameLib/GameLib.h
> +	static GameLib& GetInstance()
status設定間違えました。
修正確認しました。
お疲れ様です。 !fixed

2016-10-25 20:35 UTC, Sharoku-haga commented on Twar/Lib_Class/GameLib/GameLib.h
> +﻿/**
デバック用のフォントの関数は普通のフォントクラスとの違いを明確に分ける為、関数名をDrawDebugFontに直しました。
デバック用の時間計測関連はDebugをつけると関数名が長くなるのでコメントにてデバック用であることを明記する形で修正しております。

2016-10-25 20:38 UTC, Yottomo commented on Twar/Lib_Class/GameLib/GameLib.h
> +﻿/**
修正確認しました。
お疲れ様です。 !fixed

2016-10-26 01:21 UTC, taishi-matsumura commented on Twar/Lib_Class/GameLib/Lib/GraphicsDevice.h
> +	HWND					m_hWnd;			//!< ウィンドウハンドル
!fixed

2016-10-27 10:42 UTC, Moto0116 commented on Twar/Lib_Class/GameLib/Lib/DebugTimer.h
> +using namespace std;
usingディレクティブでstdを指定するのは良くないのでやめといたほうがいいです。
それと.hでusingディレクティブを使用すると、それをインクルードしたcppとhも影響を受けてしまうので気をつけてください。
[参考](http://ppp-lab.sakura.ne.jp/cpp/language/018.html)

どうしても使用したい場合はhではなくcppで、using宣言を使用してください。
[参考](http://www.geocities.jp/bleis_tift/cpp/namespace.html)

2016-10-27 10:52 UTC, Sharoku-haga commented on Twar/Lib_Class/GameLib/Lib/DebugTimer.h
> +using namespace std;
参考サイトの方確認致しました。
修正作業に入ります。

2016-10-27 10:54 UTC, taishi-matsumura requested changes
@Moto0116 の指摘の件、Changes Request(ApproveされるまでMergeできない)にしておきます

2016-10-27 11:19 UTC, Moto0116 commented on Twar/Lib_Class/GameLib/Lib/InputDevice.cpp
>  		return false;
返り値間違っていませんか？ !fix

2016-10-27 11:58 UTC, Sharoku-haga commented
@Moto0116 さんの指摘の件の修正完了しました。
いい機会ですので、namespaceに関して深く掘り下げて勉強してみます。
アドバイスありがとうございました。

2016-10-27 12:09 UTC, Sharoku-haga commented on Twar/Lib_Class/GameLib/Lib/InputDevice.cpp
>  		return false;
間違っています。
修正しておきました。

2016-10-27 13:04 UTC, Moto0116 commented on Twar/Lib_Class/Font/Font.h
> +	void Draw(LPCSTR pString, D3DXVECTOR2 pos, DWORD format, D3DCOLOR color);
第一引数の型間違えていませんか？
一つ上で定義しているDraw関数はLPCTSTRでしたけど。

2016-10-27 14:12 UTC, Sharoku-haga commented on Twar/Lib_Class/Font/Font.h
> +	void Draw(LPCSTR pString, D3DXVECTOR2 pos, DWORD format, D3DCOLOR color);
間違ってます。
修正しておきました。

2016-10-28 01:17 UTC, taishi-matsumura approved these changes

2016-10-29 18:15 UTC, merged