[WIP]SubSceneクラスと継承クラスの作成
TeamT-SEN/T-SEN pull request #31
Opened 2016-11-02 17:58 UTC by Sharoku-haga

#30 の作業となります。

主な作業
・SubSceneクラス作成
・上記クラスの継承クラス作成

作業予定時間
2日予定（11/05まで）

2016-11-02 23:59 UTC, Sharoku-haga commented
現在クラス名で悩んでいます。SubSceneクラスの継承クラスを作成しようとしているのですが、～SubSceneにするか、～Sceneにするか、またはなにもつけずにクラス名にするかの3つで悩んでいます。
例：OpeningSubScene、OpeningScene、Opening
意見お願いします。

2016-11-03 01:15 UTC, kakeru4 commented
僕はSubとSceneはつけなくていいと思うのでOpeningでいいと思います。

2016-11-03 07:24 UTC, Sharoku-haga commented
なるほど。何もつけなくてもいいかもしれないね。
その案でいきます。
ありがとう。

2016-11-03 08:38 UTC, taishi-matsumura requested changes
SubもSceneも付けなくて良いですが、その場合は内部クラスにするとかnamespace切るとか工夫して下さい

2016-11-05 11:46 UTC, Sharoku-haga commented
SubSceneクラスのコーディングが完了しましたので、レビューお願いします。
チームメンバーはコードレビュー後、問題なければ一番上のコメントにチェックをいれてください。
1人以上チェックがついたら、コメントをまとめて後、kakeru4にマージしてもらいます。
taishi-matsumuraのアドバイスからSubSceneクラスとその継承クラスはnamespace (名：sub_scene)できっております。

2016-11-06 06:12 UTC, taishi-matsumura reviewed
namespaceで分ける方針、了解です。

.cppは全て下記のように書かれていますが、

``` cpp
sub_scene::Battle::Battle(GameDataManager* pGameDataManager, GameTimer* pGameTimer):
```

.hと同じようにnamespaceで括ってしまった方が見やすいのでは？

``` cpp
namespace sub_scene {

Battle::Battle(GameDataManager* pGameDataManager, GameTimer* pGameTimer):

・
・
}
```

2016-11-06 06:15 UTC, taishi-matsumura reviewed
これは好みの問題なのですが、、、
自分は(C++では)namespaceの中はインデント下げない方が好きです。
[GoogleのStyleGuide](http://www.textdrop.net/google-styleguide-ja/cppguide.xml#%E5%90%8D%E5%89%8D%E7%A9%BA%E9%96%93%E3%81%AE%E6%9B%B8%E5%BC%8F)も参考にしてください。

2016-11-06 07:17 UTC, taishi-matsumura requested changes
ファイル内の行に対してのコメントに移動しました

~~enum SUBSCENE_IDをSubScene.hで定義するならnamespace sub_sceneの中に入れるべきでしょうし、 namespaceの外に出すならGameSceneとかもっと上位で定義すべきでは？~~

2016-11-06 07:28 UTC, taishi-matsumura requested changes
ファイル内の行に対してのコメントに移動しました

~~ファイルのヘッダコメントですが、~~
~~\- .hの場合「xxxクラスヘッダ」~~
~~\- .cppの場合：「xxxクラス実装」~~

~~とかで良いと思います。(あまり意味の無い形式的なものになってしまいますが、、、)~~
~~参考：http://www.denshin8.jp/den8dev/doxygen.html~~

~~それと、classにコメント付けて下さい。~~
~~これもとりあえず「xxxクラス」というbriefコメントだけで良いです。~~
~~それで意味のわからないクラスについては、そのクラスの責務や使い方等を詳細コメントで書けば良いかと。~~

2016-11-06 09:29 UTC, taishi-matsumura commented on Twar/Twar/SubScene/SubScene.h
> +class SubScene
どーーーーーーでもいいですが、
「アドバイスによる修正」よりは「レビュー指摘事項是正」とかの方が良いような、、、

2016-11-06 09:35 UTC, taishi-matsumura requested changes

2016-11-06 09:35 UTC, taishi-matsumura commented on Twar/Twar/SubScene/Battle.cpp
> +* @brief SubSceneの継承クラスであるBattleクラスのcpp
ファイルのヘッダコメントですが、
- .hの場合「xxxクラスヘッダ」
- .cppの場合：「xxxクラス実装」

とかで良いと思います。(あまり意味の無い形式的なものになってしまいますが、、、)
参考：http://www.denshin8.jp/den8dev/doxygen.html

2016-11-06 09:35 UTC, taishi-matsumura commented on Twar/Twar/SubScene/SubScene.h
> +class SubScene
classにコメント付けて下さい。 これもとりあえず「xxxクラス」というbriefコメントだけで良いです。 それで意味のわからないクラスについては、そのクラスの責務や使い方等を詳細コメントで書けば良いかと。

2016-11-06 09:37 UTC, Sharoku-haga commented on Twar/Twar/SubScene/Battle.cpp
> +* @brief SubSceneの継承クラスであるBattleクラスのcpp
コメントを修正しました。
確認お願いします。

2016-11-06 09:38 UTC, Sharoku-haga commented on Twar/Twar/SubScene/SubScene.h
> +class SubScene
クラスのコメントはSubSceneクラスだけコメントがなかったので追加しました。
確認お願いします。

2016-11-06 09:43 UTC, taishi-matsumura requested changes

2016-11-06 09:43 UTC, taishi-matsumura commented on Twar/Twar/SubScene/SubScene.h
> +enum SUBSCENE_ID
enum SUBSCENE_IDをSubScene.hで定義するならnamespace sub_sceneの中に入れるべきでしょうし、namespaceの外に出すならGameSceneとかもっと上位で定義すべきでは？

2016-11-06 10:05 UTC, masami-sugao reviewed
いきなりソースコードを見たので的外れな部分もあるかもしれません。
あくまで参考として見てもらえれば。

2016-11-06 10:05 UTC, masami-sugao commented on Twar/Twar/SubScene/Battle.h
> +	virtual~Battle();
これでコンパイラが認識できているのであれば問題はないのですが、`virtual`の後にスペースがないのは気持ち悪いです。

2016-11-06 10:05 UTC, masami-sugao commented on Twar/Twar/SubScene/Battle.h
> +	GameDataManager* m_pGameDataManager;		//!< ゲームデータ管理クラス
`m_pGameDataManager`は「クラス」ではなく「GameDataManagerクラスのインスタンスへのポインタ」なのでこの変数に対するコメントとしてはこれは的確ではないです。

2016-11-06 10:05 UTC, masami-sugao commented on Twar/Twar/SubScene/SubScene.cpp
> +m_pGameLib(&GameLib::GetInstance())
`GameLib::GetInstance()`はpublic関数で返却値も参照なので、それをメンバ変数として保持しておく必要はないように思います。
使用頻度にもよりますが、使用するところで`GameLib::GetInstance().Hoge()`とすればよいかと。

2016-11-06 10:05 UTC, masami-sugao commented on Twar/Twar/SubScene/BattleResult.h
> +	GameTimer*		 m_pGameTimer;				//!< ゲーム時間管理クラス
`SubScene`を継承する多くのクラスでメンバ変数に`SaveDataManager`, `GameDataManager`, `GameTimer`のポインタを持っていますが、少し冗長に感じます。
`SubScene`クラスのメンバ変数に持ってしまって、コンストラクタの引数の初期値をNULLにしてしまった方がすっきりしするように思います。

また、別の観点として、各クラスで利用するこの3つのオブジェクトはそれぞれ別のインスタンスなのでしょうか。
クラス名から想像するとゲーム全体で1つのインスタンスになるような気がします。
その場合はシングルトンで作成する方がよいと思います。

2016-11-07 00:25 UTC, Sharoku-haga commented on Twar/Twar/SubScene/Battle.h
> +	GameDataManager* m_pGameDataManager;		//!< ゲームデータ管理クラス
レビューありがとうございます。コメント修正しました。

2016-11-07 00:26 UTC, Sharoku-haga commented on Twar/Twar/SubScene/Battle.h
> +	virtual~Battle();
コードを修正しました。

2016-11-07 00:28 UTC, Sharoku-haga commented on Twar/Twar/SubScene/SubScene.cpp
> +m_pGameLib(&GameLib::GetInstance())
確かにその通りだと思います。修正しました。

2016-11-07 00:34 UTC, Sharoku-haga commented on Twar/Twar/SubScene/BattleResult.h
> +	GameTimer*		 m_pGameTimer;				//!< ゲーム時間管理クラス
SaveDataManager, GameDataManager, GameTimerの3つをSubSceneクラスのメンバ変数に修正しました。
シングルトンですが、レビューを受けてSaveDataManagerはシングルトンを検討しています。シングルトンにする際は別でissuesをきってから行おうと考えています。

2016-11-07 00:43 UTC, kakeru4 approved these changes

2016-11-07 01:28 UTC, taishi-matsumura approved these changes

2016-11-07 01:37 UTC, taishi-matsumura commented
コンストラクタの初期化リストの件、[GoogleのStyleGuide](http://www.textdrop.net/google-styleguide-ja/cppguide.xml#%E3%82%B3%E3%83%B3%E3%82%B9%E3%83%88%E3%83%A9%E3%82%AF%E3%82%BF%E3%82%A4%E3%83%8B%E3%82%B7%E3%83%A3%E3%83%A9%E3%82%A4%E3%82%B6%E3%83%AA%E3%82%B9%E3%83%88)には
``` cpp
// 複数行にわたる場合、スペース4つでインデントして、イニシャライザの最初の行にコロンを入れる。
MyClass::MyClass(int var)
    : some_var_(var),             // スペース4つでインデント
      some_other_var_(var + 1) {  // 一列に並べる
  ...
  DoSomething();
  ...
}
```
のように書かれていますが、Visual Studioでこれを実現するのは難しそうなので、
```
    sample( const int a, const int b )
        : a_( a )
        , b_( b )
    { }
```
が良いように思います。(https://gist.github.com/mntone/7513279)
行頭のカンマはよくやるので慣れればOKかと。

2016-11-07 01:54 UTC, merged