[WIP]FieldManagerクラスの作成
TeamT-SEN/T-SEN pull request #36
Opened 2016-11-03 01:00 UTC by kakeru4

#３５の作業になります。
作業予定
3日予定(11/5まで)

2016-11-07 02:50 UTC, kakeru4 commented
作業が完了しましたのでレビューお願いします。

2016-11-07 02:54 UTC, taishi-matsumura requested changes
pull #31 で @Sharoku-haga が受けた指摘と同様のものをまず修正して下さい。
やり直し！！

[これ](https://github.com/TeamT-SEN/T-SEN/pull/31#discussion_r86681363)とか[これ](https://github.com/TeamT-SEN/T-SEN/pull/31#discussion_r86681327)とか[これ](https://github.com/TeamT-SEN/T-SEN/pull/31#issuecomment-258729029)とか。

2016-11-07 03:24 UTC, Sharoku-haga commented on Twar/Twar/Field/FieldManager.h
> +	Sky*     m_Sky;
m_Oceneとm_Skyはポインタ変数ですが、実体はどこにありますか？
コードをみる限り、生成している場所がないように思います。

2016-11-07 03:31 UTC, Sharoku-haga commented on Twar/Twar/Field/FieldManager.h
> +	Sky*     m_Sky;
後、アクセス修飾子の順番はコーディング規約通りにお願いします。
もし順番を変える理由があるなら コメントで明記してください

2016-11-07 06:13 UTC, taishi-matsumura commented
さっき芳我が言っていた「VSへのファイル追加手順」について、下記issueを作成したので目を通しておいて下さい。
#43 VSへのフィルタやファイルの追加について

2016-11-07 06:44 UTC, kakeru4 commented
レビューで指摘されたところを修正しましたので確認をお願いします。

2016-11-07 07:35 UTC, kakeru4 commented
GameLibを使うにあたってGetDeviceがconstになっていて使えなかったので消しときました。
確認お願いします。

2016-11-07 07:37 UTC, Sharoku-haga commented
すみません。ライブラリはこっちのミスです。修正ありがとうございます。

2016-11-07 09:55 UTC, taishi-matsumura requested changes
体裁についてだけですがコメントしました。

2016-11-07 09:55 UTC, taishi-matsumura commented on Twar/Twar/Field/FieldManager.h
> +* @brief FieldManagerクラス実装
.hなので「実装」ではなく「ヘッダ」ですね。
他のヘッダファイルも同様。

2016-11-07 09:55 UTC, taishi-matsumura commented on Twar/Twar/Field/FieldManager.h
> +class FieldManager
classのコメント入れて下さい。
他のクラスも同様。
β以後の対応であればその旨レス下さい。

2016-11-07 13:45 UTC, kakeru4 commented on Twar/Twar/Field/FieldManager.h
> +* @brief FieldManagerクラス実装
しょうもないミスですみません。
修正しました。

2016-11-07 13:46 UTC, kakeru4 commented on Twar/Twar/Field/FieldManager.h
> +class FieldManager
修正完了しました。

2016-11-08 01:13 UTC, taishi-matsumura reviewed
修正確認しました。

2016-11-08 05:37 UTC, taishi-matsumura approved these changes
@kakeru4 
Mergeボタン押したら即マージできるように、conflict取ってコミット整理してforce pushしてあげて下さい。

2016-11-08 07:36 UTC, merged

2016-11-08 07:38 UTC, kakeru4 commented
コミットの整理をしたかったのですがなぜかリベースできないので今回はリベースなしでマージしました