βプレゼン後のリファクタリング
TeamT-SEN/T-SEN pull request #50
Opened 2016-11-13 15:19 UTC by Sharoku-haga

#41 の作業となります。

2016-11-14 01:20 UTC, Sharoku-haga commented
作業完了しましたので、レビューお願いします

2016-11-14 01:47 UTC, taishi-matsumura requested changes
if文は重めの処理なので、「無駄なif文が無いか」を重点的に見ました。

2016-11-14 01:47 UTC, taishi-matsumura commented on Twar/Twar/Scene/GameScene.cpp
>  		if (m_pSubScene != nullptr)
NULLチェックは良いと思いますが、m_pSubSceneがNULLの場合は明らかにバグなので、何かしらエラーメッセージを表示する等の処理が欲しいです。

2016-11-14 01:47 UTC, taishi-matsumura commented on Twar/Twar/Scene/GameScene.cpp
> +	else if( m_Step == RUN_SUBSCENE)
NULLチェックと、今のステップがRUNかのチェックは横に並ぶものでは無いと思うので、ここのelseはイヤです。

2016-11-14 01:47 UTC, taishi-matsumura commented on Twar/Twar/Scene/SceneManager.cpp
>  	if (m_pScene == nullptr)
このif文、毎フレーム走りますが、実際にこのチェックが必要なのはCREATEステップのときだけだと思います。
可読性との相談になりますが、「if文を通る回数を減らす」という発想は常に頭に置いておいて下さい。

2016-11-14 05:48 UTC, taishi-matsumura commented on Twar/Twar/Scene/SceneManager.cpp
>  	if (m_pScene == nullptr)
@Moto0116 からも質問あったので、new/deleteと関数呼び出しのコストについて記載してあるサイトを貼っておきます。
http://www.ohfuji.name/?p=360
単純計算で、 関数呼び出しよりnew/deleteの方が10倍重いみたいですね。
関数のアドレスはリンク時に決まるけど、new/deleteするアドレスは実行時に探さないといけないから当然か。
ってことは、ポリモーフィズム使って呼び出す関数を実行時に動的に決定しているところは上記のサンプルよりずっと遅くなりそうですね。

if文はこれらに比べるとずっと軽い処理ですが塵も積もればなんとやら。
で、ゲームは塵が積もるタイプのプログラムなので気を付けるに越したことは無いですねー。

2016-11-14 06:04 UTC, taishi-matsumura commented on Twar/Twar/Field/Ocean.cpp
> +	, m_Scale()
初期化リストの括弧の中身が空っぽって何？？

2016-11-14 06:11 UTC, kakeru4 commented on Twar/Twar/Field/Ocean.cpp
> +	, m_Scale()
すみません、まだ実装してないので仮置きで空っぽにしてあります。
今思えば空っぽはおかしいと思いましたので芳我さんに０を入れてもらいます。

2016-11-14 06:26 UTC, taishi-matsumura reviewed
すみません、[ref #41]のrefはrefactoringのrefだったんですね…
恥ずかしくて死にそう。

2016-11-14 06:49 UTC, taishi-matsumura commented on Twar/Twar/Scene/Scene.cpp
> +	: m_pGameLib(&GameLib::Instance())
今さらですが、`m_pGameLib`が参照型では無くポインタ型である理由は？
なんでわざわざ`GameLib::Instance()`で取れた参照に`&`付けて変換しているのかな？と思った次第。

2016-11-14 06:51 UTC, taishi-matsumura requested changes

2016-11-14 06:51 UTC, taishi-matsumura commented on Twar/Twar/Scene/SceneManager.h
> +	bool			  m_GameEnd;			//!< ゲーム終了フラグ
`m_GameEnd`って名前がイヤ

2016-11-14 06:56 UTC, masami-sugao reviewed
@taishi-matsumura 先生からレビュー依頼もらったのでまた来ました。
「リファクタリング中だから細かい部分も気になったことはコメントしてほしい」
という要望を受けてのものなので、軽い気持ちで見て下さい。

2016-11-14 06:56 UTC, masami-sugao commented on Twar/Lib_Class/GameLib/GameLib.h
>  	* @return GameLibクラス
以前の指摘と似たような事柄ですが、これも「クラス」を返却してるわけではないので違和感あります。
私だったら「Singletonインスタンス」とかにするかなー。

2016-11-14 06:56 UTC, masami-sugao commented on Twar/Twar/Scene/EndRollScene.h
> +* @brief  EndRollSceneクラスヘッダ
余分なスペースが入ってます。

2016-11-14 06:56 UTC, masami-sugao commented on Twar/Twar/Scene/GameScene.h
> +	GameDataManager*        m_pGameDataManager;		//!< GameDataManagerクラスのインスタンスへのポインタ
少し補足しておきますね。
このコメントで間違ってはいないのですが、これって`GameDataManager*`型の説明なんですよね。
ここで説明すべきは`m_pSubScene`の方なのです。

例えば
```C++
Int* m_pNumber;    //!< Int型の変数へのポインタ
```
となっていたら
「いや、それは型を見ればわかるし！知りたいのはそのInt型の変数が何かってことなんだけど。」
って思いませんか？
クラスはあくまで箱でしかなくて、中身の説明にはならないという感覚を身に付けましょう。

あと、元々書いていた「～クラス」というコメントも的確ではないですが、それを理解した上で敢えて省略して書くのであればそれでもよいと思います。
ただその場合はコーディングする人、そのコメントを見る可能性のある人みんながクラス、インスタンス、ポインタを混同していないことが前提になります。
個人的には勉強中のうちは理解度を周りに見てもらうためにもきれいな形を目指すのがよいかなと思います。

2016-11-14 06:56 UTC, masami-sugao commented on Twar/Twar/SubScene/WorldSituation.h
>  * @brief Situationクラスヘッダ
多分修正漏れ

2016-11-14 07:12 UTC, masami-sugao commented on Twar/Twar/Scene/SceneManager.h
> +	bool			  m_GameEnd;			//!< ゲーム終了フラグ
補足です。
問題は2点あります。

まず、`m_GameEnd`って名前から型が想像できない。
フラグはフラグとわかるような名前を付けるべきです。

2点目は、trueとfalseがどのような状態を示すのかが曖昧で、人によって反対の意味に取ってしまう可能性があります。

この2点を満たすためにフラグに付ける名前は`Is～`、`Has～`、`Can～`、又は三単現の動詞で始めるというコーディング規約を採用しているプロジェクトが多いです。
「boolean コーディング規約」などで検索すると例や説明を書いているページが沢山出てくるので見てみて下さい。

2016-11-14 08:33 UTC, Sharoku-haga commented on Twar/Twar/Scene/Scene.cpp
> +	: m_pGameLib(&GameLib::Instance())
勉強不足で申し訳ないですが、参照型でメンバ変数をつくれることを知らなかったです。
ですのでポインタ型にしておりました。修正しておきます。
ただ、個人的にはこのメンバ変数はポインタ型でもいいかなと思っております。
ポインタ型でかくことによって、このメンバ変数のインスタンスは別のところにあるということを明示的にあらわすことができると思うからです。

2016-11-14 08:36 UTC, Sharoku-haga commented on Twar/Twar/Scene/GameScene.cpp
>  		if (m_pSubScene != nullptr)
レビューありがとうございます。
エラーメッセージが出た後、タイトルシーンに戻る処理を追加しました。

2016-11-14 08:37 UTC, Sharoku-haga commented on Twar/Twar/Scene/GameScene.cpp
> +	else if( m_Step == RUN_SUBSCENE)
その通りだと思います。修正しておきました。

2016-11-14 08:38 UTC, Sharoku-haga commented on Twar/Twar/Scene/SceneManager.cpp
>  	if (m_pScene == nullptr)
レビュー確認致しました。
修正しておきました。

2016-11-14 08:47 UTC, Sharoku-haga commented on Twar/Twar/Field/Ocean.cpp
> +	, m_Scale()
レビュー確認致しました。
0を入れておきました。

2016-11-14 08:53 UTC, Sharoku-haga commented on Twar/Twar/Scene/SceneManager.h
> +	bool			  m_GameEnd;			//!< ゲーム終了フラグ
booleanコーディングの変数名のつけ方はネットで確認いたしました。
変数名はシンプルにisEndにしました。

2016-11-14 09:05 UTC, Sharoku-haga commented on Twar/Lib_Class/GameLib/GameLib.h
>  	* @return GameLibクラス
レビュー確認致しました。
「GameLibクラスのインスタンス」というコメントに変更しました。
今回の場合は上の行のコメントでSingletonパターンと書いているので、「Singletonインスタンス」と明記するのは冗長かなと思いこの形にしました。

2016-11-14 09:07 UTC, Sharoku-haga commented on Twar/Twar/Scene/GameScene.h
> +	GameDataManager*        m_pGameDataManager;		//!< GameDataManagerクラスのインスタンスへのポインタ
レビュー確認致しました。
今回の場合はソースを周りに見てもらうことが多いので、きれいな形でコメントを書いていこうと思います。

2016-11-14 09:27 UTC, taishi-matsumura requested changes
体裁の指摘がまだまだ続きま～す

2016-11-14 09:27 UTC, taishi-matsumura commented on Twar/Twar/Scene/SceneManager.cpp
> +	, m_isEnd(false)
他のメンバ変数は`m_`の後は大文字始まりですので、合わせるなら``m_IsEnd`では？

2016-11-14 09:27 UTC, taishi-matsumura commented on Twar/Twar/Field/Ocean.cpp
> +	: m_Pos(0.0f,0.0f,0.0f)
自動整形でスペース入りませんか？
こういう部分が勝手に変わって差分発生→コミットとならないよう、VSの書式設定はチーム内で統一しておいて下さい。
カンマの後にスペース入れないように統一しているのなら問題ありません。

2016-11-14 09:30 UTC, taishi-matsumura commented on Twar/Twar/Scene/Scene.cpp
> +	: m_pGameLib(&GameLib::Instance())
了解です。その辺がC++のウザいところですね。

2016-11-14 09:38 UTC, taishi-matsumura requested changes

2016-11-14 09:38 UTC, taishi-matsumura commented on Twar/Twar/Twar.vcxproj
> +    <LibraryPath>$(DXSDK_DIR)Lib\x86;$(SolutionDir)Debug;$(LibraryPath)</LibraryPath>
こっちはReleaseビルドの設定なので`$(SolutionDir)Debug`では？
で、こういうミスを防ぐためにDebugもReleaseも`$(OutDir)`で統一しておいては？

2016-11-14 09:41 UTC, Sharoku-haga commented on Twar/Twar/Field/Ocean.cpp
> +	: m_Pos(0.0f,0.0f,0.0f)
チームメンバーと話し合った結果、スペースをいれる方向で決まったので修正します。

2016-11-14 10:51 UTC, Sharoku-haga commented on Twar/Twar/Scene/EndRollScene.h
> +* @brief  EndRollSceneクラスヘッダ
レビュー確認致しました。
修正しました。

2016-11-14 11:24 UTC, taishi-matsumura approved these changes

2016-11-14 11:27 UTC, taishi-matsumura approved these changes
松村指摘分について、是正確認したのでApproveしておきます。

@masami-sugao あとよろ。

2016-11-14 11:47 UTC, Sharoku-haga commented on Twar/Twar/Scene/SceneManager.cpp
> +	, m_isEnd(false)
間違っております。
大文字に修正しました。

2016-11-14 11:47 UTC, Sharoku-haga commented on Twar/Twar/Twar.vcxproj
> +    <LibraryPath>$(DXSDK_DIR)Lib\x86;$(SolutionDir)Debug;$(LibraryPath)</LibraryPath>
$(OutDir)に統一しました。

2016-11-14 11:49 UTC, Sharoku-haga commented on Twar/Twar/SubScene/WorldSituation.h
>  * @brief Situationクラスヘッダ
修正漏れです。
修正しました。

2016-11-14 12:46 UTC, masami-sugao commented on Twar/Twar/Scene/Scene.cpp
> +	: m_pGameLib(&GameLib::Instance())
横レスですが、どうしてポインタ型がいいと思いつつも参照型にしたのですか？
それが悪いということではなくて、考えを聞かせて下さい。

2016-11-14 12:55 UTC, masami-sugao commented on Twar/Twar/Scene/Scene.h
> +	GameLib&		  m_GameLib;			//!< GameLibクラス
この変数名でも問題ないですが、参照型であることを明示したければ`m_rGameLib`としてもいいと思います。

2016-11-14 13:11 UTC, Sharoku-haga commented on Twar/Twar/Scene/Scene.cpp
> +	: m_pGameLib(&GameLib::Instance())
私は参照型というのがまだあまりなじめず、使いこなせていないのが現状です。なので、私は参照型よりポインタ型をよく使ってしまいます。
C++でプログラムを書くならば、参照型を使用してなれていかないといけないと思っていたところに今回のレビューをいただきました。
レビューをいただいて考えた結果、今回のプログラムではポインタ型ではなく参照型を使ってみるいい機会だと思い参照型に修正しました。

2016-11-14 13:26 UTC, Sharoku-haga commented on Twar/Twar/Scene/Scene.h
> +	GameLib&		  m_GameLib;			//!< GameLibクラス
レビュー確認致しました。
確かに参照型であることが明示できるのでとてもわかりやすいと思いました。
rをつけて修正しました。
レビューありがとうございます。

2016-11-14 13:53 UTC, masami-sugao commented on Twar/Twar/SubScene/SubSceneFactory.h
>  		static SubSceneFactory subSceneFactory;
ソース見返して思ったのですが、このクラスを継承して使う予定がない（つまりFactory Methodパターンにしない）のであれば全てstaticにしたモノステートパターンでよさそうです。
そうすれば外部から`SubSceneFactory::CreateSubScene()`と呼べるようになるので可読性が上がりますね。
モノステートパターンについては[こちら](http://www.geocities.jp/bleis_tift/cpp/singleton.html)を参考にして下さい。

2016-11-14 14:05 UTC, taishi-matsumura commented on Twar/Twar/SubScene/SubSceneFactory.h
>  		static SubSceneFactory subSceneFactory;
[このページ](http://futurismo.biz/archives/2805)に、Factory MethodパターンとAbstract Factoryパターンの違いを詳しく書いてくれています。
サンプルはJavaですが、今の君たちなら全然読めるはず。
Factory Method→Static Factory(モノステートパターン)→Abstract Factoryと順を追って説明してくれているのでわかりやすいと思います。

かく言う我々も「あれってFactory Method？Abstract Factory？」「全部staticにするのは何て言うの？」とか言いつつ調べながらコメント書いているので、心配無用(？)です。

2016-11-14 14:06 UTC, Moto0116 commented on Twar/Twar/GameData/GameDataManager.h
>  #ifndef GAMEDATA_MANAGER_H
すみません、少し気になったんですけどFieldManagerクラスのdefineはFIELDMANAGER_Hで、GameDataManagerクラスのdefineがGAMEDATA_MANAGER_Hと区切ってるのは何か理由があるんですか？
特にないなら、まとめたほうがきれいな気がします。

2016-11-14 14:12 UTC, masami-sugao commented on Twar/Twar/Scene/Scene.cpp
> +	: m_pGameLib(&GameLib::Instance())
いいどすね。ちゃんと考えがあって素敵だと思います。

2016-11-14 14:36 UTC, Sharoku-haga commented on Twar/Twar/GameData/GameDataManager.h
>  #ifndef GAMEDATA_MANAGER_H
レビュー確認致しました。
特に理由はないです。FieldManagerクラスはkakeru4が作成し、GameDataManagerクラスは私が作成した為違いがでたのだと思います。
Moto0116先輩の言う通りまとめた方がきれいだと思いますので、FIELD＿MANAGER_Hという形で修正しておきます。
コーデング規約にも特に言及してなかったので、追加しておきます。

2016-11-14 14:49 UTC, Sharoku-haga commented on Twar/Twar/SubScene/SubSceneFactory.h
>  		static SubSceneFactory subSceneFactory;
レビュー確認致しました。
モノステートパターンへの変更ですが、サイトをみて検討してみたいと思います。
もし変更する場合は、新たにissuesをきって作業を行いたいと思います。
参考サイト教えていただきありがとうございます。

2016-11-14 15:19 UTC, masami-sugao commented on Twar/Twar/GameData/GameDataManager.h
>  #ifndef GAMEDATA_MANAGER_H
であれば`GAME_DATA_MANAGER_H`にすべきかと。

2016-11-14 16:40 UTC, masami-sugao commented on Twar/Twar/Scene/SceneManager.h
> +	bool			  m_GameEnd;			//!< ゲーム終了フラグ
ソース全体を見渡すと他にもboolean型の変数、引数がありますがどこで対応しますか？

2016-11-14 16:50 UTC, masami-sugao commented on Twar/Twar/Field/Ocean.cpp
> +	: m_Pos(0.0f,0.0f,0.0f)
ソース全体見渡すとここと同じようにスペース入ってない、又は2つ入っている箇所が結構ありそうなので、新規Issue立ててまとめて修正するのがよさそうです。

2016-11-14 17:40 UTC, Sharoku-haga commented on Twar/Twar/GameData/GameDataManager.h
>  #ifndef GAMEDATA_MANAGER_H
レビュー確認致しました。
はい。その通りだと思います。
修正しておきました。

2016-11-14 17:57 UTC, Sharoku-haga commented on Twar/Twar/Field/Ocean.cpp
> +	: m_Pos(0.0f,0.0f,0.0f)
了解しました。
#51 のissuesをきりました。
このissuesでまとめて修正します。

2016-11-14 18:12 UTC, Sharoku-haga commented on Twar/Twar/Scene/SceneManager.h
> +	bool			  m_GameEnd;			//!< ゲーム終了フラグ
ソースを確認したところ、修正をしていないboolean型の変数、引数をつかっている箇所がライブラリですので、 #52 において対応しようと思います。

2016-11-14 18:47 UTC, masami-sugao reviewed
あとよろされたので全体ざっと見返しました。
レビュー範囲外でも気になった部分があったのでここに挙げておきます。
- ポインタなのにpがついていない、変数名がパスカルケースになっているなどコーディング規約に沿っていない部分がある。
- メンバ変数の初期化をメンバイニシャライザでなくコンストラクタ内で行っている部分がありますが、何か意図があるのでしょうか？
- XFileのデストラクタと`XFile::Release()`でやってることが全く同じなので、デストラクタから`XFile::Release()`を呼び出せばよさそう。
- `GameLib::UpDateDI()`は「update」で1つの単語なので`GameLib::UpdateDI()`がよさそう。
- `GameLib::ReleaseXFile()`で引数の説明に
  「@param[in] key   登録したキー、またはID。デフォルト引数は999←登録されないだろう数値を代入している要検討」
  とありますが、C#だとこういうとき`Int32.MaxValue`なんかを使います。
  C++だと`INT_MAX`が使えそうですが…C++スペシャリストな先生方に聞いてみて下さい。
- `GameLib::m_wWidth`の「w」って何のプレフィックスですか？

2016-11-14 18:47 UTC, masami-sugao commented on Twar/Twar/Field/FieldManager.cpp
>  	, m_Sky(new Sky())
`m_Ocean`, `m_Sky`はポインタのようなのでpが必要ですね。

2016-11-14 18:47 UTC, masami-sugao commented on Twar/Twar/Field/Ocean.cpp
>  	m_xFile->LoadXFile(TEXT("sea.x"));
この時点で`m_xFile`ってNULLのような気が…。
あとポインタのpがないですね。

2016-11-14 18:47 UTC, masami-sugao commented on Twar/Twar/Scene/SceneManager.cpp
> +	return m_IsEnd;
`Run()`の戻り値が終了したかどうかって違和感ありますが…そういうもんなのかな？

2016-11-14 18:53 UTC, masami-sugao commented on Twar/Twar/Scene/SceneManager.h
> +	bool			  m_GameEnd;			//!< ゲーム終了フラグ
それで問題ないと思います。
ただ、不具合修正とリファクタリングは別Issueにした方が変更点がわかりやすいので、更に別にIssue立ててもよいかなと思います。

2016-11-14 19:13 UTC, Sharoku-haga commented on Twar/Twar/Field/FieldManager.cpp
>  	, m_Sky(new Sky())
はい。その通りです。
修正しました。

2016-11-14 19:13 UTC, Sharoku-haga commented on Twar/Twar/Field/Ocean.cpp
>  	m_xFile->LoadXFile(TEXT("sea.x"));
はい。その通りです。
修正しました。

2016-11-14 19:31 UTC, Sharoku-haga commented on Twar/Twar/Scene/SceneManager.cpp
> +	return m_IsEnd;
ゲームの実行（ループ処理）をしているのがRun関数であると思っています。
なので、実行が終了したかどうかを戻り値にしても違和感がないと思い、戻り値に設定しました。

2016-11-14 20:13 UTC, Sharoku-haga commented
夜遅くまでレビューありがとうございます。
上記のレビュー範囲外でも気になった部分についてお答えさせていただきます。

・ポインタなのにpがついていない、変数名がパスカルケースになっているなどコーディング規約に沿っていない部分がある。
→こちらですが、Twarプロジェクトではそういった点は少ないと思います。ただ、Lib_Classプロジェクトだとかなり多いかと思います。
というのもLib_Classのほとんどは自分がC++を夏に学んだ直後に作成したクラス群になります。今回、ゲーム制作にあたってほぼ当時のまま使用している為、コーディング規約を無視した部分がたくさんあるかと思います。その辺りは修正していこうと思っております。

・メンバ変数の初期化をメンバイニシャライザでなくコンストラクタ内で行っている部分がありますが、何か意図があるのでしょうか？
→Twarプロジェクトだと、SubSceneクラスの継承クラスが行っていると思います。これはSubSceneの静的メンバ変数なのでメンバイニシャライザが使えない（使用してもエラーがでる）ので、コンストラクタで代入しています。
Lib_Classプロジェクトに関しては、基本的には特に意図はないです。
作成当時イニシャライザの意味がわからなかった為、試すという意味でコンストラクタとメンバイニシャライザ交互にやってみたりとちぐはぐなコードを書いてしまいました。
これに関して修正していこうと思います。

・XFileのデストラクタとXFile::Release()でやってることが全く同じなので、デストラクタからXFile::Release()を呼び出せばよさそう。
→その通りだと思います。修正します。

・GameLib::UpDateDI()は「update」で1つの単語なのでGameLib::UpdateDI()がよさそう。
→UpとDateは別の英単語だと思っていました。恥ずかしいミスです。修正しておきます。

・GameLib::ReleaseXFile()で引数の説明に 「@param[in] key 登録したキー、またはID。デフォルト引数は999←登録されないだろう数値を代入している要検討」 とありますが、C#だとこういうときInt32.MaxValueなんかを使います。 C++だとINT_MAXが使えそうですが…C++スペシャリストな先生方に聞いてみて下さい。
→INT_MAXの存在を知りませんでした。結構便利そうなマクロだと思います。先生方に聞いてみます。

GameLib::m_wWidthの「w」って何のプレフィックスですか？
→Windowsの「w」です。wWidthはウィンドウサイズの横幅という意味です。

2016-11-14 20:26 UTC, Sharoku-haga commented on Twar/Twar/Scene/SceneManager.h
> +	bool			  m_GameEnd;			//!< ゲーム終了フラグ
最初は上記の通り #52 でリファクタリングも対応しようと思ってましたが、レビューのアドバイスと結構規模的にも大きくなりそうなことを考えて #53  という形でissuesを切りました。

2016-11-15 00:29 UTC, Moto0116 commented on Twar/Twar/Scene/EndRollScene.h
> +#endif // !END_ROLL_SCENE_H
EndRoolクラスのdefineとendifのコメントには！がついているんですけど、SaveDataManagerクラスのコメントのほうは付いてなかったりするんで、統一したほうがいいんじゃないですか？

2016-11-15 01:07 UTC, masami-sugao commented on Twar/Twar/GameData/GameDataManager.h
>  #ifndef GAMEDATA_MANAGER_H
SubSceneFactory.hも直しておきましょう。

2016-11-15 01:12 UTC, masami-sugao commented on Twar/Twar/Field/Ocean.cpp
> +	: m_pXFile(nullptr)
`m_pXFile`がNULLってことを明示してほしかったわけではなくて、NULLなので`m_pXFile()->LoadFile()`は呼べないよーってことでした。

2016-11-15 01:20 UTC, masami-sugao commented
丁寧なレスありがとうございます。
これだけ答えられるってことは作るときにコピペ中心ではなくちゃんと考えて作っているということの現れだと思うので素晴らしいと思います。
Lib_Classプロジェクトは別のタイミングで作ったものだったのですね。
成長が見えていいですね。


> ・メンバ変数の初期化をメンバイニシャライザでなくコンストラクタ内で行っている部分がありますが、何か意図があるのでしょうか？
→Twarプロジェクトだと、SubSceneクラスの継承クラスが行っていると思います。これはSubSceneの静的メンバ変数なのでメンバイニシャライザが使えない（使用してもエラーがでる）ので、コンストラクタで代入しています。

折角メンバ変数を基底クラスに移動したので、初期化も移動してしまえばよいと思います。

```C++
// SubScene.h
class SubScene
{
public:
	SubScene(GameDataManager* pGameDataManager = nullptr, GameTimer* pGameTimer = nullptr, SaveDataManager* m_pSaveDataManager = nullptr);
}

// SubScene.c
SubScene::SubScene(GameDataManager* pGameDataManager, GameTimer* pGameTimer, SaveDataManager* pSaveDataManager)
	: m_rGameLib(GameLib::Instance())
	, m_pSaveDataManager(pSaveDataManager)
	, m_pGameDataManager(pGameDataManager)
	, m_pGameTimer(pGameTimer)
{
}

// Battle.c
Battle::Battle(GameDataManager* pGameDataManager, GameTimer* pGameTimer) : SubScene(pGameDataManager, pGameTimer) {}
```


>
GameLib::m_wWidthの「w」って何のプレフィックスですか？
→Windowsの「w」です。wWidthはウィンドウサイズの横幅という意味です。

さすがに省略しすぎな気もしますね。
windowの省略計としては「win」が一般的かと思います。

2016-11-15 03:14 UTC, Sharoku-haga commented on Twar/Twar/Field/Ocean.cpp
> +	: m_pXFile(nullptr)
すみません。勘違いしていました。
修正しました。

2016-11-15 03:15 UTC, Sharoku-haga commented on Twar/Twar/Scene/EndRollScene.h
> +#endif // !END_ROLL_SCENE_H
はい。その通りだと思います。
Twarプロジェクトを確認して、全て修正しておきました。

2016-11-15 03:22 UTC, Sharoku-haga commented
レビューありがとうございます。
初期化も移動完了しました。
後プレフィックスのWinに関してですが、とりあえずGameLibは修正しておきました。
他に関しては、 #53 で修正します。

2016-11-15 03:32 UTC, taishi-matsumura requested changes
@Sharoku-haga ええ加減、体裁の指摘飽きた。
VSの書式設定をちゃんと設定しているのなら自動整形機能使って整形してからコミットする等、工夫して下さい！

2016-11-15 03:32 UTC, taishi-matsumura commented on Twar/Twar/SubScene/Battle.cpp
> +	:SubScene(pGameDataManager,pGameTimer)
スペース。

2016-11-15 03:32 UTC, taishi-matsumura commented on Twar/Twar/SubScene/Home.cpp
> +	: SubScene(pGameDataManager, pGameTimer,pSaveDataManager)
スペース。

2016-11-15 03:32 UTC, taishi-matsumura commented on Twar/Twar/SubScene/WorldSituation.cpp
> +	: SubScene(pGameDataManager,pGameTimer)
スペース。

2016-11-15 03:32 UTC, taishi-matsumura commented on Twar/Twar/SubScene/Shipyard.cpp
> +	: SubScene(pGameDataManager,pGameTimer)
スペース。

2016-11-15 03:56 UTC, Sharoku-haga commented
確認不足の為、同じ指摘をさせてすみません。
自動整形による修正完了致しました。

2016-11-15 04:05 UTC, taishi-matsumura approved these changes
ifの後とかスペース入れるのね？
じゃあその設定をチームで統一して、毎回整形してからコミットするようにしといて下さいねー

もうウンザリだと思うので、一旦マージしましょか笑

2016-11-15 04:09 UTC, Sharoku-haga commented on Twar/Twar/GameData/GameDataManager.h
>  #ifndef GAMEDATA_MANAGER_H
確認ミスです。すみません。
修正しておきました。

2016-11-15 04:48 UTC, Sharoku-haga commented
了解しました。
設定は統一させます。
リベースも完了したのでkakeru4マージお願いします。

2016-11-15 04:50 UTC, merged

2016-11-15 04:58 UTC, taishi-matsumura commented
枝も消しときますねー