[WIP]LogoSceneの実装
TeamT-SEN/T-SEN pull request #96
Opened 2016-12-07 07:03 UTC by ichikawaryouya0719

#95 の作業となります。

2016-12-09 10:25 UTC, ichikawaryouya0719 commented
作業完了しました。

*仮画像を使用しています。
*動作確認済みです。

レビューお願いします。

2016-12-10 16:54 UTC, kakeru4 commented on Twar/Twar/TeamLogo/TeamLogo.h
> +	BYTE m_alpha;
少し気になったんだけど他のメンバ変数は大文字で始まってるのにm_alphaは小文字なの？
大文字か小文字かどちらかに統一してほしいです。

2016-12-10 16:55 UTC, kakeru4 commented on Twar/Twar/TeamLogo/TeamLogo.h
> +	enum LOGOSTATE
個人的な意見やけどenumは固めておいた方が見やすいかなって思います。

2016-12-10 17:02 UTC, kakeru4 commented on Twar/Twar/TeamLogo/TeamLogo.h
> +	LOGOSTATE		m_LogoState;
大丈夫ならいいんだけどメンバ変数が全部publlicになってるけど大丈夫？

2016-12-10 17:15 UTC, Sharoku-haga commented on Twar/Twar/TeamLogo/TeamLogo.h
> +	bool m_TeamLogoIsEnd;		//!<
ここ以外にもあるのだけど、メンバ変数にコメントを書いておいてください。
ヘッダーには基本的にコメントよろしくお願いします。

2016-12-10 17:24 UTC, Sharoku-haga commented on Twar/Twar/TeamLogo/TeamLogo.cpp
> +	GameLib::Instance().DrawXY(TeamLogo::TEAMLOGO_TEX, TeamLogo::TEAMLOGO_TEX, 320, 200);
ここのマジックナンバーは、定数などの方法で消してください。
後、この引数はfloatなので.fをつけるのも忘れないようにお願いします。

2016-12-10 17:26 UTC, Sharoku-haga commented on Twar/Twar/TeamLogo/TeamLogo.h
> +	enum LOGOSTATE
ここのenumだけど、FADEとINの間に_いれているなら、LOGO_FADE_INみたいにLOGOの後にも_いれてほしいかな。

2016-12-10 17:28 UTC, Sharoku-haga commented on Twar/Twar/Scene/LogoScene.h
> +	TeamLogo*  m_pTeamLogo;		//!< TitleBackgroundクラスのインスタンスへのポインタ
ここのコメント修正しておいてください。

2016-12-10 17:52 UTC, Sharoku-haga requested changes

2016-12-10 17:52 UTC, Sharoku-haga commented on Twar/Twar/TeamLogo/TeamLogo.h
> +		TEAMLOGO_TEX,			//!< タイトル背景
ここもTEAMとLOGOの間に_いれてください

2016-12-12 18:25 UTC, ichikawaryouya0719 commented
御指摘ありがとうございます。

修正しました。

2016-12-12 19:21 UTC, Sharoku-haga requested changes
一通りみました。
まだいくつか修正すべき点があるので、つらいとは思うけどよろしくお願いします。

2016-12-12 19:21 UTC, Sharoku-haga commented on Twar/Twar/Scene/LogoScene.h
> +	bool IsFadeEnd;				//!< フェードが終わったかを見る変数
LogoScene.cpp内で使われていない変数だと思われるので消しておいてください。

2016-12-12 19:21 UTC, Sharoku-haga commented on Twar/Twar/Scene/LogoScene.h
> +	TeamLogo*  m_pTeamLogo;		//!< TitleBackgroundクラスのポインタ
ここのコメントですが、まだなおっていません。
よくコメントを見てなおしてください。

2016-12-12 19:21 UTC, Sharoku-haga commented on Twar/Twar/TeamLogo/TeamLogo.h
> +	enum LOGOSTATE
ここに関しては前のレビューで言っておくべきだったところなのだけど、ここもLOGOとSTATEの間に_をいれて修正しておいてください。

2016-12-12 19:21 UTC, Sharoku-haga commented on Twar/Twar/TeamLogo/TeamLogo.h
> +	float posY;
ここの変数2つですが、メンバ変数ならm_をつけてください。

2016-12-12 19:21 UTC, Sharoku-haga commented on Twar/Twar/TeamLogo/TeamLogo.cpp
> +	posY = 240.f;
この上の2つのメンバ変数はコンストラクタ内で数値をいれる必要はありますか？
必要がないのであれば、メンバイニシャライザで初期化をしてください。

2016-12-12 19:21 UTC, Sharoku-haga commented on Twar/Twar/TeamLogo/TeamLogo.h
> +	float posY;
この変数2つにコメントもつけておいてね

2016-12-12 19:21 UTC, Sharoku-haga commented on Twar/Twar/TeamLogo/TeamLogo.cpp
> +}
ここですが、posXとposYはメンバ変数ですので、TeamLogo::はいらないので消しておいてください。

2016-12-13 04:06 UTC, ichikawaryouya0719 commented
レビューありがとうございます。

修正しました。

2016-12-13 04:16 UTC, ichikawaryouya0719 commented
コメントの修正しました。

2016-12-13 08:52 UTC, Sharoku-haga approved these changes

2016-12-13 11:11 UTC, Sharoku-haga commented
自分の指摘した部分の修正は確認致しましたので、Approvedにしておきます。
お疲れ様でした。

2016-12-14 06:55 UTC, merged